#!/usr/bin/with-contenv bash
## Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

while [ ! -f /tmp/state/99-container-init ]
do
    sleep 1
done

echo "[i] Configure Cron"
CRON_EVENT=${CRON_EVENT:-"*/2 * * * * /bin/bash /assets/cron/update.sh"}

INIT_FILE="`basename $0`-init"

if [ ! -f /tmp/state/$INIT_FILE ]; then
    sed -e "s|<CRON_EVENT>|$CRON_EVENT|g" -i /assets/cron/crontab.txt
    touch /tmp/state/$INIT_FILE
fi 

echo "[i] Start Crond"
/usr/bin/crontab /assets/cron/crontab.txt
exec /usr/sbin/crond -f -l 8 >/dev/null 2>&1
