#!/usr/bin/with-contenv bash
function Check_DB {
  until $mysqlcmd $DB_NAME -e "use $DB_NAME;"; do
    >&2 echo "[i] Mysql is unavailable - sleeping"
     sleep 1
     done

    >&2 echo "[i] Mysql is up - executing command"
}

#------MAIN------#
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
  set -x
fi

echo ''
echo "[i] Waiting for Contrainer Inited"
while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

DB_HOST=${DB_HOST:-"radius-db"}
DB_PORT=${DB_PORT:-"3306"}
DB_USER=${DB_USER:-"radius"}
DB_PASS=${DB_PASS:-"radpass"}
DB_NAME=${DB_NAME:-"radius"}

echo ''
echo "[i] Waiting for DB up"
mysqlcmd="mysql -h$DB_HOST -u$DB_USER -p$DB_PASS -A -N"

Check_DB

echo ''
echo "[i] Start Radius Server"
exec /usr/sbin/radiusd -X -f >/dev/null 2>&1
