#!/usr/bin/with-contenv bash

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
  set -x
fi

CRON_CMD=${CRON_CMD:-""}

if [ ! -f /tmp/state/`basename $0`-init ]; then
  sed -e "s|<CRON_CMD>|$CRON_CMD|g" -i /assets/cron/crontab.txt
 
 mkdir -p /tmp/state 
 touch /tmp/state/`basename $0`-init
fi
